### ISSUE TITLE
Add 1Password integration.

### ISSUE THREAD

**Issue by 3lvis** [Cocoanauts/Waves#10]

**Comment by 3lvis** [comment]
@zenangst I'm looking into this, any ideas?

**Comment by 3lvis** [comment]
So far I've found that Alfred supports 1Password integration, one idea is to find where 1Password saves it's bookmarks, and check if the current page is listed. If it is, we can show a bar in the bottom saying: Want to use your 1Password?

If you press the button, we will open 1Password suggesting the current website.

It would be great to support autofill, but I don't think this will be possible.

Something I've noticed is that the Alfred guys ask you to install the web extension, maybe there's no way to access the contents of 1Password.app but there's a way to access the contents of the extension.

**Comment by zenangst** [comment]
Been searching for anything about native integration but so far I've come up empty handed.
However, they seem to support it on iOS.

If you look in this page: http://help.agilebits.com/1Password3/requirements.html
Some non-major 3rd party browsers have support for 1Password, so I think we need to dig deeper.
Perhaps one of the plugins could be reverse engineered.

**Comment by 3lvis** [comment]
This is not supported for now. https://twitter.com/1Password/status/675443682011709441
