### ISSUE TITLE
Add Dropbox integration.

### ISSUE THREAD

**Issue by 3lvis** [Cocoanauts/Waves#12]
It would be great if preferences are sync using Dropbox.

**Comment by zenangst** [comment]
I think we need to studie the new plist-caching in Mavericks before we decide to use plists for storage. I've had some issues with synching preferences manually over iCloud.

**Comment by 3lvis** [comment]
Which problems? Dropbox Datastore helps with conflict resolution and sync.

https://www.dropbox.com/developers/datastore

**Comment by 3lvis** [comment]
iCloud is a better approach, in my opinion. One less dependency to handle. Closing.
