### ISSUE TITLE
Improved feedback when adding new Wave application

### ISSUE THREAD

**Issue by zenangst** [Cocoanauts/Waves#18]
Show errors and success statements when creation fails or succeeds.

On Success:
Opening a new window with congratulations showing two options, reveal in Finder and launch application.

On Fail:
Show direct feedback telling the user what validation failed.

**Comment by 3lvis** [comment]
Suggestions: 

It would be great if we show "App was created, wanna open it now"
"App name was already used, wanna open it now?"
